# Generated by Django 4.1.6 on 2023-02-17 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_timelog_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 8, 34, 0, 478347, tzinfo=datetime.timezone.utc)),
        ),
    ]
