# Generated by Django 4.1.6 on 2023-02-22 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_timelog_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 13, 9, 38, 165585, tzinfo=datetime.timezone.utc)),
        ),
    ]
