# Generated by Django 4.1.6 on 2023-02-24 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_timelog_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 7, 38, 9, 307464, tzinfo=datetime.timezone.utc)),
        ),
    ]
