# Django app compose

services:
  web:
    container_name: django_container
    build: .
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis


  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


  redis:
    container_name: redis_container
    image: redis
    restart: always
    ports:
      - '6379:6379'


  pghero:
    container_name: pghero
    image: ankane/pghero
    network_mode: host
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: postgres://postgres:postgres@0.0.0.0:5432
    volumes:
      - /home/daniel.perebinos@internal.ebs.md/PycharmProjects/milestone2/pghero.yml:/app/milestone2/pghero.yml
    depends_on:
      - db