# Django app compose

services:
  web:
    container_name: django_container
    build: .
    environment:
      - REDIS_HOST=redis
      - POSTGRES_NAME=milestones
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=rootpassword
      - MONGO_HOST=mongodb
      - MONGO_NAME=milestones
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
      - mongodb

  redis:
    container_name: redis_container
    image: redis
    restart: always
    ports:
      - '6379:6379'

  mongodb:
    container_name: mongodb_container
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017:27017'

  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_NAME=milestones
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  pghero:
    container_name: pghero
    image: ankane/pghero
    network_mode: host
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: postgres://postgres:postgres@0.0.0.0:5432
    volumes:
      - /home/daniel.perebinos@internal.ebs.md/PycharmProjects/milestone2/pghero.yml:/app/milestone2/pghero.yml
    depends_on:
      - db

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
#      - ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601


networks:
  es-net:
    driver: bridge